package jp.ddo.chiroru.sqllogger.proxy;

import java.lang.reflect.Method;
import java.sql.CallableStatement;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.util.HashSet;
import java.util.Set;

/**
 * <p>
 * プロキシ対象かつ返却値としてプロキシを返すメソッドは以下の通り.
 * </p>
 * <ul>
 *     <li>#createStatement()</li>
 *     <li>#createStatement(int resultSetType, int resultSetConcurrency)</li>
 *     <li>#createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability)</li>
 * </ul>
 * <ul>
 *     <li>#prepareStatement(String sql)</li>
 *     <li>#prepareStatement(String sql, int autoGeneratedKeys)</li>
 *     <li>#prepareStatement(String sql, int[] columnIndexes)</li>
 *     <li>#prepareStatement(String sql, int resultSetType, int resultSetConcurrency)</li>
 *     <li>#prepareStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability)</li>
 *     <li>#prepareStatement(String sql, String[] columnNames)</li>
 * </ul>
 * <ul>
 *     <li>#prepareCall(String sql)</li>
 *     <li>#prepareCall(String sql, int resultSetType, int resultSetConcurrency)</li>
 *     <li>#prepareCall(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability)</li>
 * </ul>
 * @author smts1008@outlook.com
 * @since 1.0.0
 */
public class ConnectionProxyStrategy
extends AbstractProxyStrategy
implements ProxyStrategy {

    private Set<String> enwrapTargetMethodName = new HashSet<>();

    public ConnectionProxyStrategy(String sessionId, Object target) {
        super(sessionId, target);
        enwrapTargetMethodName.add("createStatement");
        enwrapTargetMethodName.add("prepareStatement");
        enwrapTargetMethodName.add("prepareCall");
    }

    public boolean isProxyMethod(String methodName) {
        if (enwrapTargetMethodName.contains(methodName)) {
            return true;
        }

        return false;
    }

    @Override
    public void preProcess(Method method, Object[] arguments) {
        // TODO Auto-generated method stub
    }

    @Override
    public void postProcess(Method method, Object[] arguments) {
        // TODO Auto-generated method stub
    }

    @Override
    public Object enwrapTarget(Object o, Method method) {
        if (method.getName().equals("createStatement")) {
            return ProxyFactory.getProxy(Statement.class, (Statement)o, new StatementProxyStrategy(sessionId, o));
        } else if (method.getName().equals("prepareStatement")) {
            return ProxyFactory.getProxy(PreparedStatement.class, (PreparedStatement)o, new PreparedStatementProxyStrategy(sessionId, o));
        } else if (method.getName().equals("prepareCall")) {
            return ProxyFactory.getProxy(CallableStatement.class, (CallableStatement)o, new CallableStatementProxyStrategy(sessionId, o));
        }
        return o;
    }

}
